### ISSUE TITLE
Line 12 的单竖杠代表什么意思?

### ISSUE THREAD

**Issue by terrytan95** [shadowwalker/react-flip-over#1]
双竖杠是或的意思, 单竖杠是什么意思呢?
谢谢!

**Comment by shadowwalker** [comment]
@teeerrytan 这个在TypeScript语法中表示变量允许的类型，例如你说的L12，他允许width类型赋值成数字(例如: 100 表示100px)或者字符串(例如: 50% 表示50%的宽度)。具体请参见TypeScript文档来学习

https://github.com/shadowwalker/react-flip-over/blob/94fedc26e5b8f238768e7c2a50536e525f5362c3/src/FlipOver.tsx#L7-L15
